### ISSUE TITLE
Latest version on CocoaPods

### ISSUE THREAD

**Issue by srgray** [mxcl/LegibleError#8]
Hello, thank you for merging the latest changes. Is the latest release (1.0.3) available via CocoaPods? When I try to update my pod, it will only fetch 1.0.1.

Thanks!

**Comment by mxcl** [comment]
Yeah this is pending me finishing https://github.com/mxcl/generate-podspec

Or doing it manually.

**Comment by yonat** [comment]
Any news?

**Comment by mxcl** [comment]
https://travis-ci.com/github/mxcl/LegibleError/jobs/365189596
